# =========================================================
# 通常モードで日本語入力問題
# =========================================================
[[plugins]]
repo = 'brglng/vim-im-select'

# =========================================================
# ファイル検索
# =========================================================
[[plugins]]
repo = 'junegunn/fzf'
buid_on = '''
./install --all
'''

[[plugins]]
repo = 'junegunn/fzf.vim'
merged = 0

# =========================================================
# Markdownのプレビュー
# =========================================================
[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_ft = ['markdown', 'pandoc.markdown', 'rmd']
build = '''
cd app & yarn install
'''

# =========================================================
# Rubyジャンプ ********************未完了
# =========================================================
[[plugins]]
repo = 'szw/vim-tags'
